import PDFDocument from 'pdfkit';
import { type CommercialBillingInterval } from '@/lib/adminStore';

export type BillingInvoicePdfInput = {
  invoiceNumber: string;
  customerName?: string;
  customerEmail: string;
  organizationName?: string;
  planName: string;
  currency: string;
  firstBillAmount: number;
  firstBillSetupFee?: number;
  renewalAmount: number;
  renewalSetupFee?: number;
  billingInterval: CommercialBillingInterval;
  issuedAt: string;
  dueAt?: string;
  invoiceTitle?: string;
  note?: string;
};

function formatCurrency(amount: number, currency: string): string {
  try {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency,
      maximumFractionDigits: 2,
    }).format(amount);
  } catch {
    return `${currency} ${amount.toFixed(2)}`;
  }
}

function intervalLabel(interval: CommercialBillingInterval): string {
  return interval === 'ANNUAL' ? 'annual' : 'monthly';
}

function writeCurrencyLine(
  doc: PDFKit.PDFDocument,
  label: string,
  amount: number,
  currency: string,
  y: number,
) {
  doc.fontSize(11).fillColor('#475569').text(label, 72, y);
  doc.fontSize(11).fillColor('#0f172a').text(formatCurrency(amount, currency), 360, y, {
    align: 'right',
    width: 180,
  });
}

export async function buildBillingInvoicePdfBuffer(input: BillingInvoicePdfInput): Promise<Buffer> {
  return await new Promise<Buffer>((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 56, bufferPages: true });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk) => chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk)));
    doc.on('error', reject);
    doc.on('end', () => resolve(Buffer.concat(chunks)));

    doc
      .fillColor('#0f172a')
      .fontSize(24)
      .font('Helvetica-Bold')
      .text('Marveo', 56, 54);

    doc
      .fillColor('#475569')
      .fontSize(11)
      .font('Helvetica')
      .text('Simple billing, workspace onboarding, and commercial operations.', 56, 86);

    doc
      .roundedRect(56, 116, 482, 92, 14)
      .fillAndStroke('#f8fafc', '#dbe4f0');

    doc.fillColor('#0f172a').fontSize(18).font('Helvetica-Bold').text(input.invoiceTitle || 'Invoice', 72, 132);
    doc.fillColor('#334155').fontSize(11).font('Helvetica').text(`Invoice number: ${input.invoiceNumber}`, 72, 160);
    doc.text(`Issued at: ${new Date(input.issuedAt).toLocaleString()}`, 72, 176);
    if (input.dueAt) {
      doc.text(`Due at: ${new Date(input.dueAt).toLocaleString()}`, 292, 160);
    }

    doc
      .fillColor('#0f172a')
      .fontSize(13)
      .font('Helvetica-Bold')
      .text('Customer', 56, 234);
    doc.fontSize(11).font('Helvetica').fillColor('#334155').text(input.customerName || 'Valued customer', 56, 252);
    doc.text(input.customerEmail, 56, 268);
    if (input.organizationName) {
      doc.text(input.organizationName, 56, 284);
    }

    doc
      .fillColor('#0f172a')
      .fontSize(13)
      .font('Helvetica-Bold')
      .text('Plan summary', 56, 324);
    doc.fontSize(11).font('Helvetica').fillColor('#334155').text(input.planName, 56, 342);
    doc.text(`Billing interval: ${intervalLabel(input.billingInterval)}`, 56, 358);
    if (input.note) {
      doc.text(input.note, 56, 374, { width: 480 });
    }

    const summaryTop = 430;
    doc.roundedRect(56, summaryTop, 482, 126, 14).fillAndStroke('#ffffff', '#dbe4f0');
    doc.fillColor('#0f172a').fontSize(13).font('Helvetica-Bold').text('Billing breakdown', 72, summaryTop + 16);

    writeCurrencyLine(doc, 'First bill', input.firstBillAmount, input.currency, summaryTop + 42);
    if (typeof input.firstBillSetupFee === 'number') {
      writeCurrencyLine(doc, 'First bill setup fee', input.firstBillSetupFee, input.currency, summaryTop + 60);
    }
    writeCurrencyLine(doc, 'Renewal price', input.renewalAmount, input.currency, summaryTop + 82);
    if (typeof input.renewalSetupFee === 'number') {
      writeCurrencyLine(doc, 'Renewal setup fee', input.renewalSetupFee, input.currency, summaryTop + 100);
    }

    doc
      .fillColor('#0f172a')
      .fontSize(11)
      .font('Helvetica')
      .text(
        `After the first billing cycle, Marveo renews at the standard ${intervalLabel(input.billingInterval)} price shown above.`,
        56,
        576,
        { width: 482 },
      );

    doc
      .fillColor('#64748b')
      .fontSize(9)
      .text('Generated by Marveo commercial billing.', 56, 720, { align: 'center', width: 482 });

    doc.end();
  });
}

export function buildInvoiceEmailHtml(input: {
  invoiceNumber: string;
  planName: string;
  firstBillAmount: number;
  renewalAmount: number;
  currency: string;
  billingInterval: CommercialBillingInterval;
  customerName?: string;
}) {
  const interval = intervalLabel(input.billingInterval);
  const format = (value: number) => formatCurrency(value, input.currency);

  return `
    <div style="font-family:Arial,Helvetica,sans-serif;color:#0f172a;line-height:1.6;">
      <p style="margin:0 0 12px;">Hello ${input.customerName ? input.customerName : 'there'},</p>
      <p style="margin:0 0 12px;">Your Marveo invoice for <strong>${input.planName}</strong> is attached.</p>
      <div style="background:#f8fafc;border:1px solid #dbe4f0;border-radius:14px;padding:16px 18px;margin:16px 0;">
        <p style="margin:0 0 6px;"><strong>Invoice #:</strong> ${input.invoiceNumber}</p>
        <p style="margin:0 0 6px;"><strong>First bill:</strong> ${format(input.firstBillAmount)}</p>
        <p style="margin:0 0 6px;"><strong>Renewal price:</strong> ${format(input.renewalAmount)}</p>
        <p style="margin:0;"><strong>Billing cycle:</strong> ${interval}</p>
      </div>
      <p style="margin:0;">After the first billing cycle, the subscription renews at the standard price shown above.</p>
    </div>
  `;
}
