import type { ProfessionConfig } from '@/types/profession';

export const saasSoftwarePlatformProfession: ProfessionConfig = {
  key: 'saas-software-platform',
  professionName: 'SaaS / Software Platform',
  sector: 'Technology & Software',
  enabledModules: [
    'leads',
    'clients',
    'tickets',
    'live-chat',
    'support-center',
    'billing-lite',
    'subscriptions-lite',
    'website',
    'reports',
    'analytics',
    'finance-lite',
    'team',
    'campaigns',
    'onboarding-requests',
  ],
  dashboardWidgets: [
    'New Leads',
    'Open Tickets',
    'Live Chat Queue',
    'Website Enquiries',
    'Active Clients',
    'Active Subscriptions',
    'Monthly Revenue',
    'Support Response Time',
    'Onboarding Requests',
    'Website Setup Status',
  ],
  sidebarNavigation: [
    { label: 'Dashboard', href: '/os/dashboard' },
    { label: 'Leads', href: '/os/leads', module: 'leads' },
    { label: 'Clients', href: '/os/clients', module: 'clients' },
    { label: 'Tickets', href: '/os/tickets', module: 'tickets' },
    { label: 'Live Chat', href: '/os/support/live-chat', module: 'live-chat' },
    { label: 'Support Center', href: '/os/support', module: 'support-center' },
    { label: 'Billing', href: '/os/billing', module: 'billing-lite' },
    { label: 'Subscriptions', href: '/os/subscriptions', module: 'subscriptions-lite' },
    { label: 'Website', href: '/os/website', module: 'website' },
    { label: 'Campaigns', href: '/os/campaigns', module: 'campaigns' },
    { label: 'Reports', href: '/os/reports', module: 'reports' },
    { label: 'Analytics', href: '/os/analytics', module: 'analytics' },
    { label: 'Finance', href: '/os/finance', module: 'finance-lite' },
    { label: 'Team', href: '/os/team', module: 'team' },
    { label: 'Onboarding Requests', href: '/os/onboarding-requests', module: 'onboarding-requests' },
  ],
  onboardingQuestions: [
    { id: 'has-website', label: 'Do you already have a website?', type: 'boolean' },
    { id: 'website-platform', label: 'What platform is your website built on?', type: 'select', options: ['Next.js', 'WordPress', 'Other'] },
    { id: 'sell-subscriptions', label: 'Do you sell subscriptions?', type: 'boolean' },
    { id: 'offer-setup-services', label: 'Do you offer setup/deployment services?', type: 'boolean' },
    { id: 'provide-support', label: 'Do you provide client support?', type: 'boolean' },
    { id: 'need-live-chat', label: 'Do you want live chat on your website?', type: 'boolean' },
    { id: 'track-campaigns', label: 'Do you track leads from ads/campaigns?', type: 'boolean' },
    { id: 'enable-finance-lite', label: 'Do you want finance-lite enabled?', type: 'boolean' },
  ],
  defaultWorkflows: [
    'lead_to_demo',
    'demo_to_subscription',
    'subscription_to_onboarding',
    'support_to_retention',
  ],
  kpiCards: ['newLeads', 'openTickets', 'activeClients', 'activeSubscriptions', 'monthlyRevenue'],
  terminology: {
    lead: 'Lead',
    order: 'Subscription',
    customer: 'Client',
    ticket: 'Ticket',
    enquiry: 'Website Enquiry',
  },
  quickActions: [
    'Add Lead',
    'Create Ticket',
    'Open Live Chat',
    'Connect Website',
    'Add Client',
    'Add Expense',
    'View Reports',
    'Add Team Member',
  ],
};

export default saasSoftwarePlatformProfession;